<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:html="http://www.w3.org/TR/REC-html40">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
			<head>
				<meta charset="utf-8"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<title>XML Sitemap — BathurstAccommodation.com</title>
				<style type="text/css">
					body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; color: #1a1a1a; background: #f7f7f9; margin: 0; padding: 0; }
					.container { max-width: 980px; margin: 0 auto; padding: 32px 20px 64px; }
					h1 { margin: 0 0 6px; font-size: 26px; font-weight: 700; color: #111; }
					.lead { color: #555; margin: 0 0 24px; font-size: 14px; line-height: 1.55; }
					.lead a { color: #1f6feb; text-decoration: none; }
					.lead a:hover { text-decoration: underline; }
					.meta { color: #666; font-size: 13px; margin: 0 0 18px; }
					table { width: 100%; border-collapse: collapse; background: #fff; border: 1px solid #e6e6ea; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 2px rgba(0,0,0,0.04); }
					th, td { padding: 12px 16px; text-align: left; font-size: 13px; }
					th { background: #1a1a1a; color: #fff; font-weight: 600; text-transform: uppercase; letter-spacing: .5px; font-size: 12px; }
					tr:nth-child(even) td { background: #fafafb; }
					tr:hover td { background: #eef4ff; }
					td a { color: #1f6feb; text-decoration: none; word-break: break-all; }
					td a:hover { text-decoration: underline; }
					.badge { display: inline-block; padding: 2px 8px; border-radius: 999px; background: #eef4ff; color: #1f6feb; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: .3px; }
					footer { margin-top: 22px; color: #888; font-size: 12px; text-align: center; }
					footer a { color: #1f6feb; text-decoration: none; }
				</style>
			</head>
			<body>
				<div class="container">
					<h1>XML Sitemap</h1>
					<p class="lead">
						Generated for <strong>BathurstAccommodation.com</strong> — your guide to the best accommodation, attractions and tours in Bathurst NSW.
						This XML Sitemap is intended for search engines like Google, Bing and DuckDuckGo. You can find more information about XML sitemaps on
						<a href="https://www.sitemaps.org" rel="noopener">sitemaps.org</a>.
					</p>

					<xsl:if test="sitemap:sitemapindex">
						<p class="meta">This sitemap index contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.</p>
						<table>
							<thead>
								<tr>
									<th>Sitemap</th>
									<th width="180">Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<tr>
										<td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
										<td><xsl:value-of select="sitemap:lastmod"/></td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>

					<xsl:if test="sitemap:urlset">
						<p class="meta">This sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.</p>
						<table>
							<thead>
								<tr>
									<th>URL</th>
									<th width="120">Images</th>
									<th width="110">Priority</th>
									<th width="120">Change Freq.</th>
									<th width="180">Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
										<td><xsl:value-of select="count(image:image)"/></td>
										<td><xsl:value-of select="sitemap:priority"/></td>
										<td><span class="badge"><xsl:value-of select="sitemap:changefreq"/></span></td>
										<td><xsl:value-of select="sitemap:lastmod"/></td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>

					<footer>
						Generated by <a href="https://bathurstaccommodation.com" rel="noopener">BathurstAccommodation.com</a> · Rank Math–style XML sitemap
					</footer>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
